name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Installer les outils
        run: pip install pytest mypy

      - name: Vérifier le typage
        run: mypy lib.py

      - name: Lancer les tests
        run: pytest -v